# Generated by Django 3.2.23 on 2024-01-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=70)),
                ('province', models.CharField(max_length=70)),
                ('postal', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('arrival_date', models.CharField(max_length=50)),
                ('arrival_time', models.CharField(max_length=50)),
                ('departure_date', models.CharField(max_length=50)),
                ('departure_time', models.CharField(max_length=50)),
                ('number_person', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=80)),
            ],
        ),
    ]
